import * as THREE from 'three'
import { Suspense, useRef } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { ContactShadows, useGLTF, CameraShake } from '@react-three/drei'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Sketchfab: https://sketchfab.com/3d-models/brazillian-boot-vento-tita-6e95243a64a545aab3af43173f6b3e04
Author: https://sketchfab.com/Akaize
*/

useGLTF.preload('/assets/shoe-draco.glb')

function Shoe({ ...props }) {
  const ref = useRef()
  const { nodes, materials } = useGLTF('/assets/shoe-draco.glb')
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    ref.current.rotation.set(0.1 + Math.cos(t / 4.5) / 10, Math.sin(t / 4) / 4, 0.3 - (1 + Math.sin(t / 4)) / 8)
    ref.current.position.y = (1 + Math.sin(t / 2)) / 10
  })
  return (
    <group {...props} dispose={null}>
      <group ref={ref}>
        <group position={[-0.16, 0, -0.22]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh castShadow geometry={nodes.Object_115.geometry} material={materials['Material.002']} />
          <mesh castShadow receiveShadow geometry={nodes.Object_119.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}

function Rig({ children }) {
  const ref = useRef()
  const vec = new THREE.Vector3()
  const { camera, mouse } = useThree()
  useFrame(() => {
    // camera.position.lerp(vec.set(mouse.x * 1, 0, 3.5), 0.05)
    ref.current.position.lerp(vec.set(mouse.x * 0, mouse.y * 0.02, 0), 0.1)
    ref.current.rotation.y = THREE.MathUtils.lerp(ref.current.rotation.y, (-mouse.x * Math.PI) / 5, 0.1)
  })
  return <group ref={ref}>{children}</group>
}

export default function Scene() {
  return (
    <Canvas shadows dpr={[1, 2]} camera={{ position: [0, 0, 1.1], fov: 50 }}>
      <ambientLight intensity={2} />
      <spotLight position={[1, 6, 1.5]} angle={0.2} penumbra={1} intensity={2.5} castShadow shadow-mapSize={[2048, 2048]} />
      <spotLight position={[-5, 5, -1.5]} angle={0.03} penumbra={1} intensity={4} castShadow shadow-mapSize={[1024, 1024]} />
      <spotLight position={[5, 5, -5]} angle={0.3} penumbra={1} intensity={4} castShadow={true} shadow-mapSize={[256, 256]} color="#ffffc0" />
      <Suspense fallback={null}>
        <Rig>
        <Shoe scale={0.225} position={[0, -0.18, 0]} />
        <ContactShadows frames={1} rotation-x={[Math.PI / 2]} position={[0, -0.33, 0]} far={0.4} width={2} height={2} blur={4} />
        </Rig>
      </Suspense>
      {/* <CameraShake yawFrequency={0.2} pitchFrequency={0.2} rollFrequency={0.2} /> */}
    </Canvas>
  )
}
